// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],


  // blue protocol sidebar
  bpSidebar: [
    {
      type: 'autogenerated',
      dirName: 'blue-protocol',
    }
  ],
  // honkai nexus anima sidebar
  hnaSidebar: [
    {
      type: 'autogenerated',
      dirName: 'honkai-nexus-anima',
    }
  ],
  // skies of arcadia sidebar
  soaSidebar: [
    {
      type: 'autogenerated',
      dirName: 'skies-of-arcadia',
    }
  ],
  // mass effect sidebar
  meSidebar: [
    {
      type: 'autogenerated',
      dirName: 'mass-effect',
    }
  ],
  // persona hub sidebar
  phubSidebar: [
    {
      type: 'autogenerated',
      dirName: 'persona',
    }
  ],
  // persona 3 sidebar
  p3Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'p3-reloaded',
    }
  ],
  // persona 4 sidebar
  p4Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'p4-golden',
    }
  ],
  // persona 5 sidebar
  p5Sidebar: [
    {
      type: 'autogenerated',
      dirName: 'p5-royal',
    }
  ],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
